name: treechan
description: Browser for imageboard.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.12.0+1

environment:
  # sdk: '>=2.18.6 <=3.1.0'
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_html: ^2.2.1
  html: ^0.15.4
  swipe_image_gallery: ^0.8.0
  shared_preferences: ^2.0.17
  flexible_tree_view:
    git:
      url: https://github.com/radibobovich/flexible_tree_view.git
  grouped_list: ^5.1.2
  url_launcher: ^6.1.8
  easy_refresh: ^3.3.2+1
    # git: https://github.com/radibobovich/flutter_easy_refresh.git
  visibility_detector: ^0.3.3
  args: ^2.4.0
  photo_view: ^0.14.0
  flick_video_player: ^0.5.0
  video_player: ^2.5.2
  flutter_bloc: ^8.1.2
  settings_ui: ^2.0.2
      # an alternative that should work too
      # url: https://github.com/ko2ic/image_downloader
      # ref: 04fadbcaeebe315f8878da3ea1a3feef385f4071
  sqflite: ^2.2.6
  path: ^1.8.2
  intl: ^0.17.0
  sqflite_common_ffi: ^2.2.3
  sqlite3_flutter_libs: ^0.5.13
  share: ^2.0.4
  provider: ^6.0.5
  pausable_timer: ^1.0.0+7
  test: ^1.22.0
  noob: ^0.0.8
  should_rebuild: ^1.0.1
  extended_image: ^8.1.0
  flutter_background_service: ^5.0.1
  flutter_background_service_android: ^6.0.1
  flutter_local_notifications: ^15.1.1
  mockito: ^5.4.2
  injectable: ^2.3.0
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
    
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0

dependency_overrides:
  flutter_layout_grid: ^2.0.4
  flutter_math_fork: ^0.7.0
  flutter_svg: ^1.0.0
  path_drawing: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/test/
    - assets/dev/